apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - secret.lldap.yaml
  - secret.grafana.yaml
# production 部署 base 中定义的所有服务
patches:
  - target:
      kind: Cluster
      name: pg-shared
    patch: |
      - op: add
        path: /spec/managed/roles/-
        value:
          name: ${PG_USER_GRAFANA}
          ensure: present
          login: true
          passwordSecret:
            name: pg-grafana-credentials
  - target:
      kind: Cluster
      name: pg-shared
    patch: |
      - op: add
        path: /spec/managed/roles/-
        value:
          name: ${PG_USER_LLDAP}
          ensure: present
          login: true
          passwordSecret:
            name: pg-lldap-credentials
