apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cluster.yaml
  - ../base/lldap/
  - secret.lldap.yaml
# staging 仅部署 lldap，不需要 grafana
patches:
  - path: lldap/managed.yaml
    target:
      kind: Cluster
      name: pg-shared
